### ISSUE TITLE
Only works on the first screenshot

### ISSUE THREAD

**Issue by williamoliveira** [aikikode/fileshare#12]
Very cool app but its not working properly on my machine, I take the first screenshot all normal, then it keeps using the first screenshot taken, it does not take another

I am using Ubuntu 15.04
python-gtk2 version 2.24.0-3ubuntu4

**Comment by aikikode** [comment]
Hi,
Thanks for the feedback!

I'm aware of this behavior on latest Ubuntu version. It's actually a bug in a system library.
Looks like I'll have to release a workaround for this until it's fixed.

Please, stay tuned for updates here!

**Comment by aikikode** [comment]
I've uploaded a temporary fix for this issue. Please, update to v0.5.5.1:
https://github.com/aikikode/fileshare/releases/tag/v0.5.5.1

Did it fix the issue?

**Comment by aikikode** [comment]
I've uploaded the temporary fix. Please, install/update:
https://github.com/aikikode/fileshare/releases/tag/v0.5.5.1

Did it help?

**Comment by williamoliveira** [comment]
Yes, it works now :+1: 
thank you
