### ISSUE TITLE
Keyboard Shortcut?

### ISSUE THREAD

**Issue by NigelChen** [aikikode/fileshare#13]
I love this program. Fast, robust, no annoying GUI - It's perfect. *One* thing though, is it possible to bind the screenshot function to the prtscrn key? If it isn't possible, then that would be one thing that would make lazy me life's easier.

Awesome program, keep it up.

**Comment by NigelChen** [comment]
Didn't see the full readme.md; sorry!

**Comment by aikikode** [comment]
Thanks for feedback! Yes, shortcuts were added in #10.
