### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by neurofunk** [aikikode/fileshare#17]
I'm running Linux Mint 17.3 and when I run the application I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/indicator-fileshare", line 30, in <module>
    from gi.repository import AppIndicator3 as appindicator
ImportError: cannot import name AppIndicator3
```

**Comment by aikikode** [comment]
hi, @neurofunk 
thanks for the feedback. fileshare is using GTK 3, which is not supported on all OS.

I'll look into this issue, meanwhile could you please, search for girX.Y-appindicator package in your repository (X and Y are version numbers) and check whether it's present and installed?

**Comment by neurofunk** [comment]
Hi @aikikode,

gir1.2-appindicator3-0.1 wasn't installed. I've installed it now and everything is working.

Thank you very much, great tool!

**Comment by aikikode** [comment]
Glad to hear, thanks!
