### ISSUE TITLE
ImportError: cannot import name AppIndicator3

### ISSUE THREAD

**Issue by GronbergInfo** [aikikode/fileshare#19]
Traceback (most recent call last):
  File "/usr/local/bin/indicator-fileshare", line 30, in <module>
    from gi.repository import AppIndicator3 as appindicator
ImportError: cannot import name AppIndicator3

--
Kubuntu 17.10.

**Comment by aikikode** [comment]
Must be fixed in https://github.com/aikikode/fileshare/releases/download/0.5.7/indicator-fileshare-0.5.7.deb. Please, install it with
```
apt-get install <path to deb file>
```
